[build]
  command = "npm install jspdf jspdf-autotable @supabase/supabase-js @dnd-kit/core @dnd-kit/sortable @dnd-kit/utilities && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  ESLINT_NO_DEV_ERRORS = "true"
